# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vertilux Wiki
logo: '<img src="/public/vertilux-logo.png" atl="Vertilux Logo" width="150px">'
email: wiki@vertilux.com
description: > # this means to ignore newlines until "baseurl:"
  Vertilux is one of the largest manufacturers of Fabrics and components for the
  Window Covering Industry. Our Company started the operations in 1983 in Miami,
  Florida; and currently has 3 locations in the USA: Miami (Headquarters), Dallas
  & Los Angeles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vertilux.com.com" # the base hostname & protocol for your site
twitter_username: twitter
github_username:  github

# Build settings
markdown: kramdown

gems:
  - jemoji
